
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <div className="flex">
          <Sidebar />
          <div className="relative bg-slate-900/50 text-white min-h-screen md:flex-1">
            <div className="absolute min-h-screen w-full bg-gradient-to-br from-slate-700 via-slate-800 to-slate-900 h-full -z-10"></div>
            {children}
          </div>
        </div>
        </Providers>
      </body>
    </html>
  );
}
